# Generated by Django 4.1.7 on 2023-03-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='otp_num',
            field=models.IntegerField(),
        ),
    ]
