# Generated by Django 4.1.7 on 2023-03-06 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_onetimepassword_time_stamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimepassword',
            name='time_stamp',
        ),
    ]
