# Generated by Django 4.1.7 on 2023-03-06 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_onetimepassword_time_stamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verifytable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_num', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
