# Generated by Django 4.1.7 on 2023-05-04 00:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('texteditor_upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='readrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('rating', models.IntegerField()),
                ('hitrate', models.IntegerField()),
                ('genre', models.CharField(max_length=254)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
