# Generated by Django 4.1.7 on 2023-05-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texteditor_upload', '0002_readrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='readrate',
            name='fivestar',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readrate',
            name='fourstar',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readrate',
            name='onestar',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readrate',
            name='threestar',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readrate',
            name='twostar',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
