# Generated by Django 4.1.7 on 2023-05-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texteditor_upload', '0003_readrate_fivestar_readrate_fourstar_readrate_onestar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='avgrating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='books',
            name='fivestar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='fourstar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='hitrate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='onestar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='threestar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='twostar',
            field=models.IntegerField(default=0),
        ),
    ]
