# Generated by Django 4.1.7 on 2023-05-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texteditor_upload', '0004_books_avgrating_books_fivestar_books_fourstar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='fiveper',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='fourper',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='oneper',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='threeper',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='twoper',
            field=models.IntegerField(default=0),
        ),
    ]
