# Generated by Django 4.1.7 on 2023-05-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texteditor_upload', '0005_books_fiveper_books_fourper_books_oneper_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='avgrating',
            field=models.FloatField(default=0.0, max_length=3),
        ),
    ]
